### PR TITLE
Add Julia forwards and plotting, noise sampling and tests

### PR DESCRIPTION
**Pull request by richardt94**
This PR adds three main features:

1. Translation of forward model bindings into Julia, as well as scripts to read and plot the netCDF output of the C++ programs.

2. The capability to sample multiplicative noise into the rjmcmc1d header, and appropriate parsing functionality into the block language reader in order to activate this feature.

3. Unit tests for basic functionality in the MCMC sampler and scripts to run the tests using Travis CI when commits are pushed to the github repo.

### CODE REVIEW

**Comment by rcb547** [comment]
Hi Richard

Thanks good work.  So far I have just done a temporary/test pull as it tells me there is a merge conflict in the submodule submodules/cpp-utils.  

However I seemed to resolve the merge conflict without even doing any edits or seeing any of your mods (which does not make sense), and it all compiles no worries on Visual Studio.  

Can you advise if you have made changes in submodules/cpp-utils or not?

Ross.

**Comment by richardt94** [comment]
Hi Ross,

I forked the cpp-utils package to change the behaviour of percentile calculation to match the nearest-rank definition here: https://en.wikipedia.org/wiki/Percentile#The_nearest-rank_method

So the submodule reference is pointing to my fork of cpp-utils right now. It might make sense for me to do a separate pull request to merge that into your cpp-utils, or I can change one of my unit tests to work with your previous percentile calculation method.

**Comment by rcb547** [comment]
Hi Richard

 

How about we use the new percentile calculations that you have made.  Do you want to make a pull request for it.

 

Ross

**Comment by rcb547** [comment]
Hi Richard

I have merged your both pull request now.
Have compiled on MSVS without any problems and pushed back to ga-aem/develop.
Will test on GADI in coming days.

Good stuff.

Thanks
Ross

**Pull request merged**
